### ISSUE TITLE
Nginx doesn't start on big domain names

### ISSUE THREAD

**Issue by renatomefi** [Enrise/Basebox#1]
nginx: [emerg] could not build the server_names_hash, you should increase server_names_hash_bucket_size: 32

Sorry for putting it here, I can open a jira ticket later it was just for fast forwarding

**Comment by eXistenZNL** [comment]
@renatomefidf This issue got totally overlooked by us, sorry!

Can you inform us if this issue still exists? If it does, this might need to be fixed either here, in the Vhosting module, or in the Nginx formula. (Not sure where but we'll figure it out)

Plz let me know if this is still worth looking into.

**Comment by renatomefi** [comment]
Hey @eXistenZNL !

Yes, it will happen every time we get big domain names! I think it worth to be fixed

**Comment by sabinejansen** [comment]
@eXistenZNL see message from @renatomefidf

**Comment by renatomefi** [comment]
Whoops, sorry! haha

**Comment by eXistenZNL** [comment]
@renatomefidf thx, we'll check this.

**Comment by syphernl** [comment]
Technically this is not a basebox issue but specific to the nginx-formula. 

Either way: You can best use the `extra_config` key in your pillar to supply custom directives to your vhost, including the `server_names_hash_bucket_size`. Increasing this by default may have adverse effects and adding in another `nginx`-pillar configuration further complicates the formula. 

FWIW: On 64-bits systems the default cache size is 64 not 32.

**Comment by renatomefi** [comment]
I've done that, one year and 3 months ago :p
Which adverse effects are those?
